# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-21 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(blank=True, default=''),
        ),
    ]
